package com.ecwid.upsource.serializer

import com.google.gson.GsonBuilder

internal fun genericGsonBuiler(): GsonBuilder {
	return GsonBuilder()
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.AnalyzerProblemSeverityEnum::class.java,
			com.ecwid.upsource.rpc.projects.AnalyzerProblemSeverityEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.AppConfigurationProblemEnum::class.java,
			com.ecwid.upsource.rpc.projects.AppConfigurationProblemEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.BuildStatusEnum::class.java,
			com.ecwid.upsource.rpc.projects.BuildStatusEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.fileordirectorycontent.CapabilityFlagsEnum::class.java,
			com.ecwid.upsource.rpc.fileordirectorycontent.CapabilityFlagsEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ConflictTypeEnum::class.java,
			com.ecwid.upsource.rpc.projects.ConflictTypeEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.DiffTypeEnum::class.java,
			com.ecwid.upsource.rpc.projects.DiffTypeEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.users.EmailStatusEnum::class.java,
			com.ecwid.upsource.rpc.users.EmailStatusEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.FeedTypeEnum::class.java,
			com.ecwid.upsource.rpc.projects.FeedTypeEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.fileordirectorycontent.FileWarningLevelEnum::class.java,
			com.ecwid.upsource.rpc.fileordirectorycontent.FileWarningLevelEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.fileordirectorycontent.GutterMarkEnum::class.java,
			com.ecwid.upsource.rpc.fileordirectorycontent.GutterMarkEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.fileordirectorycontent.InspectionSeverityEnum::class.java,
			com.ecwid.upsource.rpc.fileordirectorycontent.InspectionSeverityEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.issuetrackers.IssueRequiredFieldTypeEnum::class.java,
			com.ecwid.upsource.rpc.issuetrackers.IssueRequiredFieldTypeEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.OwnershipSummaryEnum::class.java,
			com.ecwid.upsource.rpc.projects.OwnershipSummaryEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ParticipantStateEnum::class.java,
			com.ecwid.upsource.rpc.projects.ParticipantStateEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ProjectStateEnum::class.java,
			com.ecwid.upsource.rpc.projects.ProjectStateEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ReadEnum::class.java,
			com.ecwid.upsource.rpc.projects.ReadEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.analytics.ReviewCoverageStateEnum::class.java,
			com.ecwid.upsource.rpc.analytics.ReviewCoverageStateEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ReviewFeedSortEnum::class.java,
			com.ecwid.upsource.rpc.projects.ReviewFeedSortEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.ReviewStateEnum::class.java,
			com.ecwid.upsource.rpc.projects.ReviewStateEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.RevisionReachabilityEnum::class.java,
			com.ecwid.upsource.rpc.projects.RevisionReachabilityEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.RevisionStateEnum::class.java,
			com.ecwid.upsource.rpc.projects.RevisionStateEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.users.RoleInReviewEnum::class.java,
			com.ecwid.upsource.rpc.users.RoleInReviewEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.SyncResultEnum::class.java,
			com.ecwid.upsource.rpc.projects.SyncResultEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.projects.TestConnectionStatusEnum::class.java,
			com.ecwid.upsource.rpc.projects.TestConnectionStatusEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.misc.TestPOP3MailboxStatusEnum::class.java,
			com.ecwid.upsource.rpc.misc.TestPOP3MailboxStatusEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.analytics.TimeUnitEnum::class.java,
			com.ecwid.upsource.rpc.analytics.TimeUnitEnumTypeAdapter()
		)
		.registerTypeAdapter(
			com.ecwid.upsource.rpc.misc.WebhookEventEnum::class.java,
			com.ecwid.upsource.rpc.misc.WebhookEventEnumTypeAdapter()
		)
}
