// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param items 
 */
@Suppress("unused")
data class AchievementsListDTO(
	val items: List<AchievementDTO> = emptyList()
)