// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param isAllowed Whether the user has the right to create projects
 * @param message Optional text message
 */
@Suppress("unused")
data class CheckCanCreateProjectResponseDTO(
	/**
	 * Whether the user has the right to create projects (required)
	 */
	val isAllowed: Boolean,

	/**
	 * Optional text message (optional)
	 */
	val message: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		isAllowed = false,
		message = null
	)
}
