// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param emails Emails with either a "soft bounce" or a "hard bounce" status
 */
data class EmailBouncesResponseDTO(
	/**
	 * Emails with either a "soft bounce" or a "hard bounce" status (repeated)
	 */
	val emails: List<String> = emptyList()
)