// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param serverPath A full path to the server
 */
data class ExportDataResponseDTO(
	/**
	 * A full path to the server (required)
	 */
	val serverPath: String
) {
	internal constructor() : this(
		serverPath = ""
	)
}
