// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

data class GetProjectSettingRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * See GetSettingRequestDTO parameters (required)
	 */
	val request: GetSettingRequestDTO
) {
	internal constructor() : this(
		projectId = "",
		request = GetSettingRequestDTO()
	)
}
