// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param projectId Project ID in Upsource
 * @param request See GetSettingRequestDTO parameters
 */
data class GetProjectSettingRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * See GetSettingRequestDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.misc.GetSettingRequestDTO
	 */
	val request: GetSettingRequestDTO
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		request = GetSettingRequestDTO()
	)
}
