// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param key Setting key
 */
data class GetSettingRequestDTO(
	/**
	 * Setting key (required)
	 */
	val key: String
) {
	internal constructor() : this(
		key = ""
	)
}
