// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param value User setting value
 */
@Suppress("unused")
data class GetSettingResponseDTO(
	/**
	 * User setting value (optional)
	 */
	val value: String? = null
)