// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

data class GetSettingResponseDTO(
	/**
	 * User setting value (optional)
	 */
	val value: String? = null
)