// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param isReadOnly Whether the server is in read-only mode
 * @param description Describes the reason for enabling read-only mode (if any)
 */
data class ReadOnlyModeDTO(
	/**
	 * Whether the server is in read-only mode (required)
	 */
	val isReadOnly: Boolean,

	/**
	 * Describes the reason for enabling read-only mode (if any) (optional)
	 */
	val description: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		isReadOnly = false,
		description = null
	)
}
