// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

data class SetProjectSettingRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * See SetSettingRequestDTO parameters (required)
	 */
	val request: SetSettingRequestDTO
) {
	internal constructor() : this(
		projectId = "",
		request = SetSettingRequestDTO()
	)
}
