// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param key Setting key
 * @param value Setting value
 */
@Suppress("unused")
data class SetSettingRequestDTO(
	/**
	 * Setting key (required)
	 */
	val key: String,

	/**
	 * Setting value (required)
	 */
	val value: String
) {
	@Suppress("unused")
	internal constructor() : this(
		key = "",
		value = ""
	)
}

