// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param status Mailbox status. OK (1); LoginFailed (2); ConnectionFailed (3);
 * @param message Optional text message
 */
@Suppress("unused")
data class TestPOP3MailboxResponseDTO(
	/**
	 * Mailbox status. OK (1); LoginFailed (2); ConnectionFailed (3); (required)
	 */
	val status: TestPOP3MailboxStatusEnum,

	/**
	 * Optional text message (optional)
	 */
	val message: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		status = TestPOP3MailboxStatusEnum.OK,
		message = null
	)
}

