// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param userId User ID in Upsource
 * @param timezoneOffset Timezone offset
 */
data class UpdateUserTimezoneDTO(
	/**
	 * User ID in Upsource (required)
	 */
	val userId: String,

	/**
	 * Timezone offset (required)
	 */
	val timezoneOffset: Int
) {
	internal constructor() : this(
		userId = "",
		timezoneOffset = 0
	)
}
