// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param count
 */
@Suppress("unused")
data class UserAchievementsCountDTO(
	val count: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		count = 0
	)
}

