// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param count 
 */
data class UserAchievementsCountDTO(
	val count: Int
) {
	internal constructor() : this(
		count = 0
	)
}
