// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.misc

/**
 * @param text 
 */
data class UserAgreementTextDTO(
	val text: String
) {
	@Suppress("unused")
	internal constructor() : this(
		text = ""
	)
}
