// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

data class IssueTrackerProvidersListDTO(
	/**
	 * See IssueTrackerProviderDTO parameters (repeated)
	 */
	val providers: List<IssueTrackerProviderDTO> = emptyList()
)