// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param providerKey Issue tracker provider key ("YouTrack", "JIRA")
 * @param settings Settings used to set up the integration (e.g server URL, login credentials, project ID in the issue tracker)
 */
@Suppress("unused")
data class IssueTrackerProviderSettingsDTO(
	/**
	 * Issue tracker provider key ("YouTrack", "JIRA") (required)
	 */
	val providerKey: String,

	/**
	 * Settings used to set up the integration (e.g server URL, login credentials, project ID in the issue tracker) (repeated)
	 */
	val settings: List<IssueTrackerProviderSettingDTO> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		providerKey = "",
		settings = emptyList()
	)
}
