// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param fieldId Field ID (see IssueFieldDTO)
 * @param valueId Value ID (see IssueFieldValueDTO)
 */
@Suppress("unused")
data class IssueFieldValueIdDTO(
	/**
	 * Field ID (see IssueFieldDTO) (required)
	 */
	val fieldId: String,

	/**
	 * Value ID (see IssueFieldValueDTO) (required)
	 */
	val valueId: String
) {
	@Suppress("unused")
	internal constructor() : this(
		fieldId = "",
		valueId = ""
	)
}

