// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param providers See IssueTrackerProviderDTO parameters
 */
@Suppress("unused")
data class IssueTrackerProvidersListDTO(
	/**
	 * See IssueTrackerProviderDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.issuetrackers.IssueTrackerProviderDTO
	 */
	val providers: List<IssueTrackerProviderDTO> = emptyList()
)