// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param valueId Value ID
 * @param name Value title
 * @param html HTML presentation of the value, e.g. a <span> with some inline styles
 */
@Suppress("unused")
data class IssueFieldValueDTO(
	/**
	 * Value ID (required)
	 */
	val valueId: String,

	/**
	 * Value title (required)
	 */
	val name: String,

	/**
	 * HTML presentation of the value, e.g. a <span> with some inline styles (required)
	 */
	val html: String
) {
	@Suppress("unused")
	internal constructor() : this(
		valueId = "",
		name = "",
		html = ""
	)
}

