// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param name Setting key
 * @param value Setting value
 */
data class IssueTrackerProviderSettingDTO(
	/**
	 * Setting key (required)
	 */
	val name: String,

	/**
	 * Setting value (required)
	 */
	val value: String
) {
	internal constructor() : this(
		name = "",
		value = ""
	)
}
