// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param projectId Project ID in Upsource
 * @param issueId Issue ID
 */
data class IssueInfoRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Issue ID (required)
	 */
	val issueId: IssueIdDTO
) {
	internal constructor() : this(
		projectId = "",
		issueId = IssueIdDTO()
	)
}
