// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

data class IssueTrackerProjectDetailsDTO(
	/**
	 * Issue tracker provider key ("YouTrack", "JIRA") (required)
	 */
	val providerKey: String,

	/**
	 * Issue tracker project URL (required)
	 */
	val projectUrl: String,

	/**
	 * See IssueFieldDTO parameters (repeated)
	 */
	val field: List<IssueFieldDTO> = emptyList(),

	/**
	 * Whether an issue can be created (required)
	 */
	val canCreateIssue: Boolean,

	/**
	 * See IssueRequiredFieldDTO parameters (repeated)
	 */
	val requiredField: List<IssueRequiredFieldDTO> = emptyList()
) {
	internal constructor() : this(
		providerKey = "",
		projectUrl = "",
		field = emptyList(),
		canCreateIssue = false,
		requiredField = emptyList()
	)
}
