// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.issuetrackers

/**
 * @param providerKey Issue tracker provider key ("YouTrack", "JIRA")
 * @param projectUrl Issue tracker project URL
 * @param field See IssueFieldDTO parameters
 * @param canCreateIssue Whether an issue can be created
 * @param requiredField See IssueRequiredFieldDTO parameters
 * @param projectKey Issue tracker project key
 */
data class IssueTrackerProjectDetailsDTO(
	/**
	 * Issue tracker provider key ("YouTrack", "JIRA") (required)
	 */
	val providerKey: String,

	/**
	 * Issue tracker project URL (required)
	 */
	val projectUrl: String,

	/**
	 * See IssueFieldDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.issuetrackers.IssueFieldDTO
	 */
	val field: List<IssueFieldDTO> = emptyList(),

	/**
	 * Whether an issue can be created (required)
	 */
	val canCreateIssue: Boolean,

	/**
	 * See IssueRequiredFieldDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.issuetrackers.IssueRequiredFieldDTO
	 */
	val requiredField: List<IssueRequiredFieldDTO> = emptyList(),

	/**
	 * Issue tracker project key (optional)
	 */
	val projectKey: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		providerKey = "",
		projectUrl = "",
		field = emptyList(),
		canCreateIssue = false,
		requiredField = emptyList(),
		projectKey = null
	)
}
