// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

data class ElementDocumentationDTO(
	/**
	 * Text of the element documentation (optional)
	 */
	val docString: String? = null
)