// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param branches The list of matched branches
 * @param hasMore Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request
 */
@Suppress("unused")
data class FindBranchResponseDTO(
	/**
	 * The list of matched branches (repeated)
	 */
	val branches: List<String> = emptyList(),

	/**
	 * Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request (required)
	 */
	val hasMore: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		branches = emptyList(),
		hasMore = false
	)
}
