// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

data class FindUsagesItemDTO(
	/**
	 * See NavigationTargetItemDTO parameters (required)
	 */
	val navigationTarget: NavigationTargetItemDTO,

	/**
	 * Preview text (required)
	 */
	val previewText: String,

	/**
	 * Start offset (required)
	 */
	val startOffsetInPreview: Int,

	/**
	 * End offset (required)
	 */
	val endOffsetInPreview: Int,

	/**
	 * Line number (required)
	 */
	val lineNumber: Int,

	/**
	 * Identifies if this usage is semantic-sensitive or not (required)
	 */
	val isImportant: Boolean
) {
	internal constructor() : this(
		navigationTarget = NavigationTargetItemDTO(),
		previewText = "",
		startOffsetInPreview = 0,
		endOffsetInPreview = 0,
		lineNumber = 0,
		isImportant = false
	)
}
