// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param projectName Holds the project name
 */
@Suppress("unused")
data class TextSearchProjectDetails(
	/**
	 * Holds the project name (required)
	 */
	val projectName: String
) {
	@Suppress("unused")
	internal constructor() : this(
		projectName = ""
	)
}
