// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param items The items that match the search query
 */
@Suppress("unused")
data class TextSearchResponseDTO(
	/**
	 * The items that match the search query (repeated)
	 */
	val items: List<TextSearchItem> = emptyList()
)