// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param projectId Project ID in Upsource
 * @param query The search query
 * @param filenameFilter File name filter
 * @param ignoreDeleted Ignore matches in deleted files
 * @param ignoreArchived Whether to search in archived projects
 */
data class TextSearchRequestDTO(
	/**
	 * Project ID in Upsource (optional)
	 */
	val projectId: String? = null,

	/**
	 * The search query (required)
	 */
	val query: String,

	/**
	 * File name filter (optional)
	 */
	val filenameFilter: String? = null,

	/**
	 * Ignore matches in deleted files (required)
	 */
	val ignoreDeleted: Boolean,

	/**
	 * Whether to search in archived projects (required)
	 */
	val ignoreArchived: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = null,
		query = "",
		filenameFilter = null,
		ignoreDeleted = false,
		ignoreArchived = false
	)
}
