// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param originElement Original element. See PsiElementIdDTO parameters
 * @param anotherRevisionId ID of the other revision
 * @param isAnotherOld Whether the other revision is older
 */
data class UsagesDiffByAnotherRevisionRequestDTO(
	/**
	 * Original element. See PsiElementIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.PsiElementIdDTO
	 */
	val originElement: PsiElementIdDTO,

	/**
	 * ID of the other revision (required)
	 */
	val anotherRevisionId: String,

	/**
	 * Whether the other revision is older (required)
	 */
	val isAnotherOld: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		originElement = PsiElementIdDTO(),
		anotherRevisionId = "",
		isAnotherOld = false
	)
}
