// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param oldElement Old element. See PsiElementIdDTO parameters
 * @param newElement New element. See PsiElementIdDTO parameters
 */
data class UsagesDiffFullRequestDTO(
	/**
	 * Old element. See PsiElementIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.PsiElementIdDTO
	 */
	val oldElement: PsiElementIdDTO,

	/**
	 * New element. See PsiElementIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.PsiElementIdDTO
	 */
	val newElement: PsiElementIdDTO
) {
	internal constructor() : this(
		oldElement = PsiElementIdDTO(),
		newElement = PsiElementIdDTO()
	)
}
