// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param originElement Original element. See PsiElementIdDTO parameters
 * @param newRevisionId ID of the new revision
 * @param boundaryRevisionId ID of the boundary revision
 */
data class UsagesDiffByBoundaryRevisionsRequestDTO(
	/**
	 * Original element. See PsiElementIdDTO parameters (required)
	 * 
	 * @see PsiElementIdDTO
	 */
	val originElement: PsiElementIdDTO,

	/**
	 * ID of the new revision (required)
	 */
	val newRevisionId: String,

	/**
	 * ID of the boundary revision (required)
	 */
	val boundaryRevisionId: String
) {
	internal constructor() : this(
		originElement = PsiElementIdDTO(),
		newRevisionId = "",
		boundaryRevisionId = ""
	)
}
