// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.findusages

/**
 * @param oldFilePathToRoot See FilePathToRootDTO parameters
 * @param newFilePathToRoot See FilePathToRootDTO parameters
 * @param removedUsage See FindUsagesItemDTO parameters
 * @param sameUsage See SameUsagesDTO parameters
 * @param addedUsage See FindUsagesItemDTO parameters
 */
data class UsagesDiffDTO(
	/**
	 * See FilePathToRootDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.FilePathToRootDTO
	 */
	val oldFilePathToRoot: FilePathToRootDTO? = null,

	/**
	 * See FilePathToRootDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.FilePathToRootDTO
	 */
	val newFilePathToRoot: FilePathToRootDTO? = null,

	/**
	 * See FindUsagesItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.FindUsagesItemDTO
	 */
	val removedUsage: List<FindUsagesItemDTO> = emptyList(),

	/**
	 * See SameUsagesDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.SameUsagesDTO
	 */
	val sameUsage: List<SameUsagesDTO> = emptyList(),

	/**
	 * See FindUsagesItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.findusages.FindUsagesItemDTO
	 */
	val addedUsage: List<FindUsagesItemDTO> = emptyList()
)