// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param commitsCount Number of commits merged
 * @param branches List of merged branches
 */
@Suppress("unused")
data class MergedToDefaultBranchEventBean(
	/**
	 * Number of commits merged (required)
	 */
	val commitsCount: Int,

	/**
	 * List of merged branches (repeated)
	 */
	val branches: List<String> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		commitsCount = 0,
		branches = emptyList()
	)
}
