// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param revisionId Revision ID
 * @param branches List of branches
 * @param author Author ID
 * @param message Commit message
 * @param date Commit date
 */
@Suppress("unused")
data class NewRevisionEventBean(
	/**
	 * Revision ID (required)
	 */
	val revisionId: String,

	/**
	 * List of branches (repeated)
	 */
	val branches: List<String> = emptyList(),

	/**
	 * Author ID (optional)
	 */
	val author: String? = null,

	/**
	 * Commit message (optional)
	 */
	val message: String? = null,

	/**
	 * Commit date (optional)
	 */
	val date: Long? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		revisionId = "",
		branches = emptyList(),
		author = null,
		message = null,
		date = null
	)
}

