// Generated by the codegen. Please DO NOT EDIT!
// source: jackson-enum.ftl

package com.ecwid.upsource.rpc.events

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.deser.std.StdDeserializer
import com.fasterxml.jackson.databind.ser.std.StdSerializer

class ParticipantStateDeserializer : StdDeserializer<ParticipantState>(ParticipantState::class.java) {
	override fun deserialize(p: JsonParser, ctxt: DeserializationContext): ParticipantState? {
		return ParticipantState.fromValue(p.byteValue)
	}
}

class ParticipantStateSerializer : StdSerializer<ParticipantState>(ParticipantState::class.java) {
	override fun serialize(value: ParticipantState, gen: JsonGenerator, provider: SerializerProvider) {
		gen.writeNumber(value.value.toShort())
	}
}
