// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param participant Participant user info
 * @param oldState Old state
 * @param newState New state
 */
data class ParticipantStateChangedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Participant user info (required)
	 */
	val participant: UserIdBean,

	/**
	 * Old state (required)
	 */
	val oldState: ParticipantState,

	/**
	 * New state (required)
	 */
	val newState: ParticipantState
) {
	internal constructor() : this(
		base = FeedEventBean(),
		participant = UserIdBean(),
		oldState = ParticipantState.UNREAD,
		newState = ParticipantState.UNREAD
	)
}
