// Generated by the codegen. Please DO NOT EDIT!
// source: jackson-enum.ftl

package com.ecwid.upsource.rpc.events

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.deser.std.StdDeserializer
import com.fasterxml.jackson.databind.ser.std.StdSerializer

class ParticipantRoleDeserializer : StdDeserializer<ParticipantRole>(ParticipantRole::class.java) {
	override fun deserialize(p: JsonParser, ctxt: DeserializationContext): ParticipantRole? {
		return ParticipantRole.fromValue(p.byteValue)
	}
}

class ParticipantRoleSerializer : StdSerializer<ParticipantRole>(ParticipantRole::class.java) {
	override fun serialize(value: ParticipantRole, gen: JsonGenerator, provider: SerializerProvider) {
		gen.writeNumber(value.value.toShort())
	}
}
