// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param pullRequest Branch name
 */
data class PullRequestMergedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Branch name (required)
	 */
	val pullRequest: String
) {
	internal constructor() : this(
		base = FeedEventBean(),
		pullRequest = ""
	)
}
