// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param discussionId Discussion ID
 * @param commentId Comment ID
 * @param reactionId Reaction ID
 * @param wasAdded Whether the reaction was added or removed
 * @param actor User who toggled reaction
 */
@Suppress("unused")
data class ReactionToggledEventBean(
	/**
	 * Discussion ID (required)
	 */
	val discussionId: String,

	/**
	 * Comment ID (required)
	 */
	val commentId: String,

	/**
	 * Reaction ID (required)
	 */
	val reactionId: String,

	/**
	 * Whether the reaction was added or removed (required)
	 */
	val wasAdded: Boolean,

	/**
	 * User who toggled reaction (required)
	 */
	val actor: UserIdBean
) {
	@Suppress("unused")
	internal constructor() : this(
		discussionId = "",
		commentId = "",
		reactionId = "",
		wasAdded = false,
		actor = UserIdBean()
	)
}
