// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param participant Participant user info
 * @param formerRole The role participant had before being removed from review
 */
data class RemovedParticipantFromReviewFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Participant user info (required)
	 */
	val participant: UserIdBean,

	/**
	 * The role participant had before being removed from review (required)
	 */
	val formerRole: ParticipantRole
) {
	internal constructor() : this(
		base = FeedEventBean(),
		participant = UserIdBean(),
		formerRole = ParticipantRole.AUTHOR
	)
}
