// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param deadline Review due date (Unix timestamp)
 */
@Suppress("unused")
data class ReviewDeadlineUpdatedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Review due date (Unix timestamp) (optional)
	 */
	val deadline: Long? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		base = FeedEventBean(),
		deadline = null
	)
}
