// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param reviewId Review ID
 * @param labelId Label ID
 * @param labelName Label name
 * @param wasAdded Whether the label was added or removed
 * @param actor User who changed label
 */
@Suppress("unused")
data class ReviewLabelChangedEventBean(
	/**
	 * Review ID (required)
	 */
	val reviewId: String,

	/**
	 * Label ID (required)
	 */
	val labelId: String,

	/**
	 * Label name (required)
	 */
	val labelName: String,

	/**
	 * Whether the label was added or removed (required)
	 */
	val wasAdded: Boolean,

	/**
	 * User who changed label (required)
	 */
	val actor: UserIdBean
) {
	@Suppress("unused")
	internal constructor() : this(
		reviewId = "",
		labelId = "",
		labelName = "",
		wasAdded = false,
		actor = UserIdBean()
	)
}

