// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param revisionId Target Revision ID
 */
@Suppress("unused")
data class ReviewSquashedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Target Revision ID (required)
	 */
	val revisionId: String
) {
	@Suppress("unused")
	internal constructor() : this(
		base = FeedEventBean(),
		revisionId = ""
	)
}

