// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param reviewId Review ID
 */
data class ReviewRemovedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Review ID (required)
	 */
	val reviewId: String
) {
	internal constructor() : this(
		base = FeedEventBean(),
		reviewId = ""
	)
}
