// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param revisionIds List of revision IDs
 */
@Suppress("unused")
data class RevisionRemovedFromReviewFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * List of revision IDs (repeated)
	 */
	val revisionIds: List<String> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		base = FeedEventBean(),
		revisionIds = emptyList()
	)
}
