// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param base Base feed event
 * @param oldState Old state
 * @param newState New state
 */
data class ReviewStateChangedFeedEventBean(
	/**
	 * Base feed event (required)
	 */
	val base: FeedEventBean,

	/**
	 * Old state (required)
	 */
	val oldState: ReviewState,

	/**
	 * New state (required)
	 */
	val newState: ReviewState
) {
	internal constructor() : this(
		base = FeedEventBean(),
		oldState = ReviewState.OPEN,
		newState = ReviewState.OPEN
	)
}
