// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.events

/**
 * @param userId 
 * @param userName 
 * @param userEmail 
 */
data class UserIdBean(
	val userId: String? = null,

	val userName: String? = null,

	val userEmail: String? = null
)