// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param projectId Project ID in Upsource
 * @param pattern Search query, e.g. part of the name
 * @param limit Number of results to return
 */
data class FindUsersRequestDTO(
	/**
	 * Project ID in Upsource (optional)
	 */
	val projectId: String? = null,

	/**
	 * Search query, e.g. part of the name (required)
	 */
	val pattern: String,

	/**
	 * Number of results to return (required)
	 */
	val limit: Int
) {
	internal constructor() : this(
		projectId = null,
		pattern = "",
		limit = 0
	)
}
