// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param projectId Project ID in Upsource
 * @param lastCommitTime Unix timestamp of the last commit
 */
@Suppress("unused")
data class UserProjectInfoDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Unix timestamp of the last commit (required)
	 */
	val lastCommitTime: Long
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		lastCommitTime = 0L
	)
}
