// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

data class UsersPresenceInfoResponseDTO(
	/**
	 * See UserPresenceInfoDTO parameters (repeated)
	 */
	val presences: List<UserPresenceInfoDTO> = emptyList()
)