// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

data class UserProjectsResponseDTO(
	/**
	 * See UserProjectInfoDTO parameters (repeated)
	 */
	val projects: List<UserProjectInfoDTO> = emptyList()
)