// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param presences See UserPresenceInfoDTO parameters
 */
data class UsersPresenceInfoResponseDTO(
	/**
	 * See UserPresenceInfoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.users.UserPresenceInfoDTO
	 */
	val presences: List<UserPresenceInfoDTO> = emptyList()
)