// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

data class UserInfoResponseDTO(
	/**
	 * See FullUserInfoDTO parameters (repeated)
	 */
	val infos: List<FullUserInfoDTO> = emptyList()
)