// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param userId Upsource user ID
 * @param isOnline Whether the user is online
 * @param absentUntil Absence end date, if the user is currently on leave
 */
data class UserPresenceInfoDTO(
	/**
	 * Upsource user ID (required)
	 */
	val userId: String,

	/**
	 * Whether the user is online (required)
	 */
	val isOnline: Boolean,

	/**
	 * Absence end date, if the user is currently on leave (optional)
	 */
	val absentUntil: Long? = null
) {
	internal constructor() : this(
		userId = "",
		isOnline = false,
		absentUntil = null
	)
}
