// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param infos See FullUserInfoDTO parameters
 */
data class UserInfoResponseDTO(
	/**
	 * See FullUserInfoDTO parameters (repeated)
	 * 
	 * @see FullUserInfoDTO
	 */
	val infos: List<FullUserInfoDTO> = emptyList()
)