// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param ids A list of user IDs to request the full user info for
 */
@Suppress("unused")
data class UserInfoRequestDTO(
	/**
	 * A list of user IDs to request the full user info for (repeated)
	 */
	val ids: List<String> = emptyList()
)