// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.users

/**
 * @param userId Upsource user ID
 * @param commitTimestampFilter Project update timestamp to limit the returned projects by
 */
@Suppress("unused")
data class UserProjectsRequestDTO(
	/**
	 * Upsource user ID (required)
	 */
	val userId: String,

	/**
	 * Project update timestamp to limit the returned projects by (required)
	 */
	val commitTimestampFilter: Long
) {
	@Suppress("unused")
	internal constructor() : this(
		userId = "",
		commitTimestampFilter = 0L
	)
}

