// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param inspections See InspectionCodeMarkupItemDTO parameters
 * @param fileLevel See FileWarningLevelEnum parameters
 */
data class CodeInspectionsDTO(
	/**
	 * See InspectionCodeMarkupItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.InspectionCodeMarkupItemDTO
	 */
	val inspections: List<InspectionCodeMarkupItemDTO> = emptyList(),

	/**
	 * See FileWarningLevelEnum parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.FileWarningLevelEnum
	 */
	val fileLevel: FileWarningLevelEnum
) {
	@Suppress("unused")
	internal constructor() : this(
		inspections = emptyList(),
		fileLevel = FileWarningLevelEnum.NONE
	)
}
