// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param text File text
 * @param foldings See FoldingInfoDTO parameters
 * @param isSyntaxSupported Whether syntax markup is available for this file type
 * @param syntax See TextMarkupDTO parameters
 */
@Suppress("unused")
data class FileContentDTO(
	/**
	 * File text (required)
	 */
	val text: String,

	/**
	 * See FoldingInfoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.FoldingInfoDTO
	 */
	val foldings: List<FoldingInfoDTO> = emptyList(),

	/**
	 * Whether syntax markup is available for this file type (optional)
	 */
	val isSyntaxSupported: Boolean? = null,

	/**
	 * See TextMarkupDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.TextMarkupDTO
	 */
	val syntax: List<TextMarkupDTO> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		text = "",
		foldings = emptyList(),
		isSyntaxSupported = null,
		syntax = emptyList()
	)
}
