// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param hasPsi Whether the code model is available for a file
 * @param psiStatusMessage PSI status message, e.g. a failure to provide code intelligence or another message regarding the file in general
 * @param referenceMarkup See FileReferenceCodeMarkupDTO parameters
 * @param textMarkup See FileTextMarkupDTO parameters
 * @param gutterMarks See GutterCodeMarkupsDTO parameters
 * @param inspections See CodeInspectionsDTO parameters
 * @param externalInspections External inspections
 */
data class FilePsiResponseDTO(
	/**
	 * Whether the code model is available for a file (optional)
	 */
	val hasPsi: Boolean? = null,

	/**
	 * PSI status message, e.g. a failure to provide code intelligence or another message regarding the file in general (optional)
	 */
	val psiStatusMessage: String? = null,

	/**
	 * See FileReferenceCodeMarkupDTO parameters (optional)
	 * 
	 * @see FileReferenceCodeMarkupDTO
	 */
	val referenceMarkup: FileReferenceCodeMarkupDTO? = null,

	/**
	 * See FileTextMarkupDTO parameters (optional)
	 * 
	 * @see FileTextMarkupDTO
	 */
	val textMarkup: FileTextMarkupDTO? = null,

	/**
	 * See GutterCodeMarkupsDTO parameters (optional)
	 * 
	 * @see GutterCodeMarkupsDTO
	 */
	val gutterMarks: GutterCodeMarkupsDTO? = null,

	/**
	 * See CodeInspectionsDTO parameters (optional)
	 * 
	 * @see CodeInspectionsDTO
	 */
	val inspections: CodeInspectionsDTO? = null,

	/**
	 * External inspections (repeated)
	 */
	val externalInspections: List<InspectionCodeMarkupItemDTO> = emptyList()
)