// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param contentType See FileContentTypeDTO parameters
 * @param fileContent See FileContentDTO parameters
 */
data class FileContentResponseDTO(
	/**
	 * See FileContentTypeDTO parameters (required)
	 * 
	 * @see FileContentTypeDTO
	 */
	val contentType: FileContentTypeDTO,

	/**
	 * See FileContentDTO parameters (optional)
	 * 
	 * @see FileContentDTO
	 */
	val fileContent: FileContentDTO? = null
) {
	internal constructor() : this(
		contentType = FileContentTypeDTO(),
		fileContent = null
	)
}
