// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param fromOffset Start offset of the foldable range
 * @param toOffset End offset of the foldable range
 * @param isInitialCollapsed Whether the range is initially collapsed
 * @param collapsedText Text to be displayed in place of the folded range
 */
@Suppress("unused")
data class FoldingInfoDTO(
	/**
	 * Start offset of the foldable range (required)
	 */
	val fromOffset: Int,

	/**
	 * End offset of the foldable range (required)
	 */
	val toOffset: Int,

	/**
	 * Whether the range is initially collapsed (required)
	 */
	val isInitialCollapsed: Boolean,

	/**
	 * Text to be displayed in place of the folded range (required)
	 */
	val collapsedText: String
) {
	@Suppress("unused")
	internal constructor() : this(
		fromOffset = 0,
		toOffset = 0,
		isInitialCollapsed = false,
		collapsedText = ""
	)
}

