// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param items See GutterCodeMarkupItemDTO parameters
 */
data class GutterCodeMarkupsDTO(
	/**
	 * See GutterCodeMarkupItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.GutterCodeMarkupItemDTO
	 */
	val items: List<GutterCodeMarkupItemDTO> = emptyList()
)