// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param range See RangeDTO parameters
 * @param gutterMark See GutterMarkEnum parameters
 * @param relatedSemanticMarkup Index in 'referenceMarkup' list this gutter mark corresponds to
 */
data class GutterCodeMarkupItemDTO(
	/**
	 * See RangeDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.RangeDTO
	 */
	val range: com.ecwid.upsource.rpc.ids.RangeDTO,

	/**
	 * See GutterMarkEnum parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.GutterMarkEnum
	 */
	val gutterMark: List<GutterMarkEnum> = emptyList(),

	/**
	 * Index in 'referenceMarkup' list this gutter mark corresponds to (required)
	 */
	val relatedSemanticMarkup: Int
) {
	internal constructor() : this(
		range = com.ecwid.upsource.rpc.ids.RangeDTO(),
		gutterMark = emptyList(),
		relatedSemanticMarkup = 0
	)
}
