// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param diffForFile See InspectionsDiffForFileDTO parameters
 */
data class InspectionsDiffDTO(
	/**
	 * See InspectionsDiffForFileDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.InspectionsDiffForFileDTO
	 */
	val diffForFile: List<InspectionsDiffForFileDTO> = emptyList()
)