// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param range See RangeDTO parameters
 * @param textAttribute See TextAttributeDTO parameters
 * @param message Inspection message
 * @param severity See InspectionSeverityEnum parameters
 * @param textAttributesKey Name (if any) of this markup key, given by IntelliJ IDEA
 */
@Suppress("unused")
data class InspectionCodeMarkupItemDTO(
	/**
	 * See RangeDTO parameters (required)
	 *
	 * @see com.ecwid.upsource.rpc.ids.RangeDTO
	 */
	val range: com.ecwid.upsource.rpc.ids.RangeDTO,

	/**
	 * See TextAttributeDTO parameters (required)
	 *
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.TextAttributeDTO
	 */
	val textAttribute: TextAttributeDTO,

	/**
	 * Inspection message (required)
	 */
	val message: String,

	/**
	 * See InspectionSeverityEnum parameters (required)
	 *
	 * @see com.ecwid.upsource.rpc.fileordirectorycontent.InspectionSeverityEnum
	 */
	val severity: InspectionSeverityEnum,

	/**
	 * Name (if any) of this markup key, given by IntelliJ IDEA (optional)
	 */
	val textAttributesKey: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		range = com.ecwid.upsource.rpc.ids.RangeDTO(),
		textAttribute = TextAttributeDTO(),
		message = "",
		severity = InspectionSeverityEnum.INFORMATION,
		textAttributesKey = null
	)
}

