// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

data class InspectionsDiffDTO(
	/**
	 * See InspectionsDiffForFileDTO parameters (repeated)
	 */
	val diffForFile: List<InspectionsDiffForFileDTO> = emptyList()
)