// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param targetId ID of the target element
 * @param startOffset Start offset
 * @param endOffset End offset
 */
@Suppress("unused")
data class LocalDeclarationRangeDTO(
	/**
	 * ID of the target element (required)
	 */
	val targetId: Int,

	/**
	 * Start offset (required)
	 */
	val startOffset: Int,

	/**
	 * End offset (required)
	 */
	val endOffset: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		targetId = 0,
		startOffset = 0,
		endOffset = 0
	)
}
