// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.fileordirectorycontent

/**
 * @param fgColor Foreground color
 * @param bgColor Background color
 * @param fontStyle Font style (italic, bold)
 * @param effectStyle Text effect (underline, wave underline, strikeout, etc.)
 * @param effectColor Effect color
 * @param errorStripeColor Error stripe color
 */
@Suppress("unused")
data class TextAttributeDTO(
	/**
	 * Foreground color (optional)
	 */
	val fgColor: String? = null,

	/**
	 * Background color (optional)
	 */
	val bgColor: String? = null,

	/**
	 * Font style (italic, bold) (optional)
	 */
	val fontStyle: String? = null,

	/**
	 * Text effect (underline, wave underline, strikeout, etc.) (optional)
	 */
	val effectStyle: String? = null,

	/**
	 * Effect color (optional)
	 */
	val effectColor: String? = null,

	/**
	 * Error stripe color (optional)
	 */
	val errorStripeColor: String? = null
)