// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

data class CommitterUserInfo(
	/**
	 * VCS committer name (required)
	 */
	val committer: String,

	/**
	 * User ID of the committer (required)
	 */
	val userId: String
) {
	internal constructor() : this(
		committer = "",
		userId = ""
	)
}
