// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param totalCommits Total number of commits
 * @param offsiteCommits Number of commits that didn't affect any module
 * @param modulesTouched Number of modules affected
 */
@Suppress("unused")
data class CommitsSummaryDTO(
	/**
	 * Total number of commits (required)
	 */
	val totalCommits: Int,

	/**
	 * Number of commits that didn't affect any module (required)
	 */
	val offsiteCommits: Int,

	/**
	 * Number of modules affected (required)
	 */
	val modulesTouched: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		totalCommits = 0,
		offsiteCommits = 0,
		modulesTouched = 0
	)
}
