// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param committer User ID of the committer
 * @param items See ModuleValue parameters
 */
data class CommitterModuleValue(
	/**
	 * User ID of the committer (required)
	 */
	val committer: String,

	/**
	 * See ModuleValue parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.ModuleValue
	 */
	val items: List<ModuleValue> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		committer = "",
		items = emptyList()
	)
}
