// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param committer User ID of the committer
 * @param items See TimeValue parameters
 */
@Suppress("unused")
data class CommitterTimeValue(
	/**
	 * User ID of the committer (required)
	 */
	val committer: String,

	/**
	 * See TimeValue parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.TimeValue
	 */
	val items: List<TimeValue> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		committer = "",
		items = emptyList()
	)
}

