// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param timestamp Unix timestamp of the frame
 * @param deltas Counts of file edits since the previous frame
 */
@Suppress("unused")
data class FileHistoryFrameDTO(
	/**
	 * Unix timestamp of the frame (required)
	 */
	val timestamp: Long,

	/**
	 * Counts of file edits since the previous frame (repeated)
	 */
	val deltas: List<Int> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		timestamp = 0L,
		deltas = emptyList()
	)
}
