// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param module Name of the project module
 * @param items See TimeValue parameters
 */
@Suppress("unused")
data class ModuleTimeValue(
	/**
	 * Name of the project module (required)
	 */
	val module: String,

	/**
	 * See TimeValue parameters (repeated)
	 *
	 * @see com.ecwid.upsource.rpc.analytics.TimeValue
	 */
	val items: List<TimeValue> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		module = "",
		items = emptyList()
	)
}

