// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param entries See ProjectTreeMapEntryDTO parameters
 */
@Suppress("unused")
data class ProjectTreeMapDTO(
	/**
	 * See ProjectTreeMapEntryDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.ProjectTreeMapEntryDTO
	 */
	val entries: List<ProjectTreeMapEntryDTO> = emptyList()
)