// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param items See TimeValue parameters
 * @param modules Names of project modules
 * @param stats See AnalyzerStats parameters
 */
data class ProjectActivityDTO(
	/**
	 * See TimeValue parameters (repeated)
	 * 
	 * @see TimeValue
	 */
	val items: List<TimeValue> = emptyList(),

	/**
	 * Names of project modules (repeated)
	 */
	val modules: List<String> = emptyList(),

	/**
	 * See AnalyzerStats parameters (required)
	 * 
	 * @see AnalyzerStats
	 */
	val stats: AnalyzerStats
) {
	internal constructor() : this(
		items = emptyList(),
		modules = emptyList(),
		stats = AnalyzerStats()
	)
}
