// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param items See CommitterModuleValue parameters
 * @param users See CommitterUserInfo parameters
 * @param modules Names of the project modules
 * @param stats See AnalyzerStats parameters
 */
data class ResponsibilityDistributionDTO(
	/**
	 * See CommitterModuleValue parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.CommitterModuleValue
	 */
	val items: List<CommitterModuleValue> = emptyList(),

	/**
	 * See CommitterUserInfo parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.CommitterUserInfo
	 */
	val users: List<CommitterUserInfo> = emptyList(),

	/**
	 * Names of the project modules (repeated)
	 */
	val modules: List<String> = emptyList(),

	/**
	 * See AnalyzerStats parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.analytics.AnalyzerStats
	 */
	val stats: AnalyzerStats
) {
	@Suppress("unused")
	internal constructor() : this(
		items = emptyList(),
		users = emptyList(),
		modules = emptyList(),
		stats = AnalyzerStats()
	)
}
