// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param userId Upsource user ID
 */
@Suppress("unused")
data class ReviewTimeStatisticsRequestDTO(
	/**
	 * Upsource user ID (required)
	 */
	val userId: String
) {
	@Suppress("unused")
	internal constructor() : this(
		userId = ""
	)
}
