// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

data class ReviewTimeStatisticsRequestDTO(
	/**
	 * Upsource user ID (required)
	 */
	val userId: String
) {
	internal constructor() : this(
		userId = ""
	)
}
