// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param projectId Project ID in Upsource
 * @param fromTime Unix timestamp
 * @param toTime Unix timestamp
 */
@Suppress("unused")
data class ReviewStatisticsRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Unix timestamp (optional)
	 */
	val fromTime: Long? = null,

	/**
	 * Unix timestamp (optional)
	 */
	val toTime: Long? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		fromTime = null,
		toTime = null
	)
}
