// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param projectId Project ID in Upsource
 * @param fromTime Unix timestamp, only reviews that were updated later are considered
 */
data class ReviewersGraphRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Unix timestamp, only reviews that were updated later are considered (optional)
	 */
	val fromTime: Long? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		fromTime = null
	)
}
