// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param distribution Durations of review iterations, sorted in ascending order
 */
data class ReviewTimeStatisticsDTO(
	/**
	 * Durations of review iterations, sorted in ascending order (repeated)
	 */
	val distribution: List<Long> = emptyList()
)