// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param time Unix timestamp
 * @param value The value associated with the timestamp
 */
@Suppress("unused")
data class TimeValue(
	/**
	 * Unix timestamp (required)
	 */
	val time: Long,

	/**
	 * The value associated with the timestamp (required)
	 */
	val value: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		time = 0L,
		value = 0
	)
}
