// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.analytics

/**
 * @param userId Upsource user ID
 * @param value The value associated with the user ID
 */
@Suppress("unused")
data class UserValue(
	/**
	 * Upsource user ID (required)
	 */
	val userId: String,

	/**
	 * The value associated with the user ID (required)
	 */
	val value: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		userId = "",
		value = 0
	)
}
