// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param discussionId Discussion ID
 * @param text Text of the comment being added
 * @param parentId An ID of the comment you are replying to
 * @param markupType Currently not in use
 */
data class AddCommentRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Discussion ID (required)
	 */
	val discussionId: String,

	/**
	 * Text of the comment being added (required)
	 */
	val text: String,

	/**
	 * An ID of the comment you are replying to (optional)
	 */
	val parentId: String? = null,

	/**
	 * Currently not in use (optional)
	 */
	val markupType: String? = null
) {
	internal constructor() : this(
		projectId = "",
		discussionId = "",
		text = "",
		parentId = null,
		markupType = null
	)
}
