// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class AllRolesResponseDTO(
	/**
	 * See RoleDetailsDTO parameters (repeated)
	 */
	val roleDetails: List<RoleDetailsDTO> = emptyList()
)