// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param roleDetails See RoleDetailsDTO parameters
 */
data class AllRolesResponseDTO(
	/**
	 * See RoleDetailsDTO parameters (repeated)
	 * 
	 * @see RoleDetailsDTO
	 */
	val roleDetails: List<RoleDetailsDTO> = emptyList()
)