// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param range Text range associated with an anchor
 * @param fileId File associated with an anchor
 * @param revisionId VCS revision ID
 * @param inlineInRevision Whether a comment was left in the inline diff
 */
data class AnchorDTO(
	/**
	 * Text range associated with an anchor (optional)
	 */
	val range: com.ecwid.upsource.rpc.ids.RangeDTO? = null,

	/**
	 * File associated with an anchor (optional)
	 */
	val fileId: String? = null,

	/**
	 * VCS revision ID (optional)
	 */
	val revisionId: String? = null,

	/**
	 * Whether a comment was left in the inline diff (optional)
	 */
	val inlineInRevision: String? = null
)