// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param name Branch name
 * @param lastRevision See RevisionInfoDTO parameters
 * @param isDefault Whether the branch is a default one
 * @param stats See BranchStatsDTO parameters
 * @param isHosted Whether the branch is from a hosted repository
 * @param reviewId ID of the branch review, if one exists
 */
data class BranchDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Branch name (required)
	 */
	val name: String,

	/**
	 * See RevisionInfoDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionInfoDTO
	 */
	val lastRevision: RevisionInfoDTO,

	/**
	 * Whether the branch is a default one (required)
	 */
	val isDefault: Boolean,

	/**
	 * See BranchStatsDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.BranchStatsDTO
	 */
	val stats: BranchStatsDTO,

	/**
	 * Whether the branch is from a hosted repository (required)
	 */
	val isHosted: Boolean,

	/**
	 * ID of the branch review, if one exists (optional)
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		name = "",
		lastRevision = RevisionInfoDTO(),
		isDefault = false,
		stats = BranchStatsDTO(),
		isHosted = false,
		reviewId = null
	)
}
