// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revisions See RevisionInfoDTO parameters
 * @param graph See RevisionListGraphDTO parameters
 */
@Suppress("unused")
data class BranchGraphDTO(
	/**
	 * See RevisionInfoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionInfoDTO
	 */
	val revisions: List<RevisionInfoDTO> = emptyList(),

	/**
	 * See RevisionListGraphDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionListGraphDTO
	 */
	val graph: RevisionListGraphDTO
) {
	@Suppress("unused")
	internal constructor() : this(
		revisions = emptyList(),
		graph = RevisionListGraphDTO()
	)
}

