// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param isAllowed A branch review can be created
 * @param message A message explaining the reason why a review can't be created
 */
data class CanCreateBranchReviewDTO(
	/**
	 * A branch review can be created (required)
	 */
	val isAllowed: Boolean,

	/**
	 * A message explaining the reason why a review can't be created (optional)
	 */
	val message: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		isAllowed = false,
		message = null
	)
}
