// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param patterns See CodeReviewPattern
 */
@Suppress("unused")
data class CodeReviewPatternsDTO(
	/**
	 * See CodeReviewPattern (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.CodeReviewPattern
	 */
	val patterns: List<CodeReviewPattern> = emptyList()
)