// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class CodeReviewPatternsDTO(
	/**
	 * See CodeReviewPattern (repeated)
	 */
	val patterns: List<CodeReviewPattern> = emptyList()
)