// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param pattern Code review ID pattern
 */
@Suppress("unused")
data class CodeReviewPattern(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Code review ID pattern (required)
	 */
	val pattern: String
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		pattern = ""
	)
}

