// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revisions See RevisionInfoDTO parameters
 * @param graph See RevisionListGraphDTO parameters
 * @param pathToBaseLength The length of the displayed path from the branching revision to the base
 * @param fullPathToBaseLength The actual length of the path from the branching revision to the base
 * @param pathToSecondLength The length of the displayed path from the branching revision to the second revision
 * @param fullPathToSecondLength The actual length of the path from the branching revision to the second revision
 */
@Suppress("unused")
data class CompareGraphDTO(
	/**
	 * See RevisionInfoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionInfoDTO
	 */
	val revisions: List<RevisionInfoDTO> = emptyList(),

	/**
	 * See RevisionListGraphDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionListGraphDTO
	 */
	val graph: RevisionListGraphDTO,

	/**
	 * The length of the displayed path from the branching revision to the base (required)
	 */
	val pathToBaseLength: Int,

	/**
	 * The actual length of the path from the branching revision to the base (required)
	 */
	val fullPathToBaseLength: Int,

	/**
	 * The length of the displayed path from the branching revision to the second revision (required)
	 */
	val pathToSecondLength: Int,

	/**
	 * The actual length of the path from the branching revision to the second revision (required)
	 */
	val fullPathToSecondLength: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		revisions = emptyList(),
		graph = RevisionListGraphDTO(),
		pathToBaseLength = 0,
		fullPathToBaseLength = 0,
		pathToSecondLength = 0,
		fullPathToSecondLength = 0
	)
}
