// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param completedCount Number of reviewers who completed the review, either by accepting or raising concern about the changes
 * @param reviewersCount Total number of reviewers
 * @param hasConcern Whether someone has raised a concern about the changes
 */
@Suppress("unused")
data class CompletionRateDTO(
	/**
	 * Number of reviewers who completed the review, either by accepting or raising concern about the changes (required)
	 */
	val completedCount: Int,

	/**
	 * Total number of reviewers (required)
	 */
	val reviewersCount: Int,

	/**
	 * Whether someone has raised a concern about the changes (required)
	 */
	val hasConcern: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		completedCount = 0,
		reviewersCount = 0,
		hasConcern = false
	)
}

