// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param anchor See AnchorDTO parameters
 * @param reviewId See ReviewIdDTO parameters
 * @param text Text of the discussion
 * @param projectId Project ID in Upsource
 * @param markupType Currently not in use
 * @param labels Discussion labels. See LabelDTO parameters
 */
@Suppress("unused")
data class CreateDiscussionRequestDTO(
	/**
	 * See AnchorDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.AnchorDTO
	 */
	val anchor: AnchorDTO,

	/**
	 * See ReviewIdDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.ReviewIdDTO
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO? = null,

	/**
	 * Text of the discussion (required)
	 */
	val text: String,

	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Currently not in use (optional)
	 */
	val markupType: String? = null,

	/**
	 * Discussion labels. See LabelDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.LabelDTO
	 */
	val labels: List<LabelDTO> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		anchor = AnchorDTO(),
		reviewId = null,
		text = "",
		projectId = "",
		markupType = null,
		labels = emptyList()
	)
}
