// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param newProjectId An ID of the new Upsource project
 * @param settings See ProjectSettingsDTO parameters
 * @param custom Optional custom settings
 */
data class CreateProjectRequestDTO(
	/**
	 * An ID of the new Upsource project (required)
	 */
	val newProjectId: String,

	/**
	 * See ProjectSettingsDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ProjectSettingsDTO
	 */
	val settings: ProjectSettingsDTO,

	/**
	 * Optional custom settings (repeated)
	 */
	val custom: List<com.ecwid.upsource.rpc.misc.SetSettingRequestDTO> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		newProjectId = "",
		settings = ProjectSettingsDTO(),
		custom = emptyList()
	)
}
