// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param discussionId ID of the discussion
 * @param reviewId See ReviewIdDTO parameters
 */
@Suppress("unused")
data class DiscussionInReviewDTO(
	/**
	 * ID of the discussion (required)
	 */
	val discussionId: String,

	/**
	 * See ReviewIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.ReviewIdDTO
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO
) {
	@Suppress("unused")
	internal constructor() : this(
		discussionId = "",
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO()
	)
}

