// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param fileId Path to file
 * @param discussions Discussions contained in the file. See DiscussionsInFileDTO parameters
 */
data class DiscussionsGroupDTO(
	/**
	 * Path to file (optional)
	 */
	val fileId: String? = null,

	/**
	 * Discussions contained in the file. See DiscussionsInFileDTO parameters (required)
	 * 
	 * @see DiscussionsInFileDTO
	 */
	val discussions: DiscussionsInFileDTO
) {
	internal constructor() : this(
		fileId = null,
		discussions = DiscussionsInFileDTO()
	)
}
