// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revisionId VCS revision ID
 * @param fileName A full path of the file starting with a slash (e.g. /folder/subfolder/file.txt )
 * @param discussionInFile See DiscussionInFileDTO parameters
 */
@Suppress("unused")
data class DiscussionInFileWithFileDTO(
	/**
	 * VCS revision ID (optional)
	 */
	val revisionId: String? = null,

	/**
	 * A full path of the file starting with a slash (e.g. /folder/subfolder/file.txt ) (required)
	 */
	val fileName: String,

	/**
	 * See DiscussionInFileDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.DiscussionInFileDTO
	 */
	val discussionInFile: DiscussionInFileDTO
) {
	@Suppress("unused")
	internal constructor() : this(
		revisionId = null,
		fileName = "",
		discussionInFile = DiscussionInFileDTO()
	)
}
