// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param discussions See DiscussionInFileDTO parameters
 */
@Suppress("unused")
data class DiscussionsInFileDTO(
	/**
	 * See DiscussionInFileDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.DiscussionInFileDTO
	 */
	val discussions: List<DiscussionInFileDTO> = emptyList()
)