// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class DiscussionsInRevisionDTO(
	/**
	 * See DiscussionsGroupDTO parameters (repeated)
	 */
	val groups: List<DiscussionsGroupDTO> = emptyList()
)