// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param discussions See DiscussionInFileWithFileDTO parameters
 */
data class DiscussionsInFilesDTO(
	/**
	 * See DiscussionInFileWithFileDTO parameters (repeated)
	 * 
	 * @see DiscussionInFileWithFileDTO
	 */
	val discussions: List<DiscussionInFileWithFileDTO> = emptyList()
)