// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param groups See DiscussionsGroupDTO parameters
 */
data class DiscussionsInRevisionDTO(
	/**
	 * See DiscussionsGroupDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.DiscussionsGroupDTO
	 */
	val groups: List<DiscussionsGroupDTO> = emptyList()
)