// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param discussions See DiscussionInFileDTO parameters
 * @param hasMore Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request
 * @param totalCount Total number of discussions matching query
 */
data class DiscussionsInProjectDTO(
	/**
	 * See DiscussionInFileDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.DiscussionInFileDTO
	 */
	val discussions: List<DiscussionInFileDTO> = emptyList(),

	/**
	 * Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request (optional)
	 */
	val hasMore: Boolean? = null,

	/**
	 * Total number of discussions matching query (optional)
	 */
	val totalCount: Int? = null
)