// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param fileId Path to file
 * @param discussions Discussions contained in the file. See DiscussionsInFileDTO parameters
 */
@Suppress("unused")
data class DiscussionsGroupDTO(
	/**
	 * Path to file (optional)
	 */
	val fileId: String? = null,

	/**
	 * Discussions contained in the file. See DiscussionsInFileDTO parameters (required)
	 *
	 * @see com.ecwid.upsource.rpc.projects.DiscussionsInFileDTO
	 */
	val discussions: DiscussionsInFileDTO
) {
	@Suppress("unused")
	internal constructor() : this(
		fileId = null,
		discussions = DiscussionsInFileDTO()
	)
}

