// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class EditLabelsRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Discussion labels IDs (repeated)
	 */
	val labelId: List<String> = emptyList()
) {
	internal constructor() : this(
		projectId = "",
		labelId = emptyList()
	)
}
