// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param feedItems See FeedItemDTO parameters
 * @param hasMore Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request
 */
data class FeedDTO(
	/**
	 * See FeedItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FeedItemDTO
	 */
	val feedItems: List<FeedItemDTO> = emptyList(),

	/**
	 * Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request (required)
	 */
	val hasMore: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		feedItems = emptyList(),
		hasMore = false
	)
}
