// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param fileId See FileInRevisionDTO parameters
 * @param sourceRevisionId The source revision from which the branch originated
 * @param baseBranch The base branch to compare against
 * @param diffType Type of change (see DiffTypeEnum)
 * @param ignoreWhitespace Whether to ignore whitespace changes
 * @param contextLines Number of context lines around the modified fragment
 */
@Suppress("unused")
data class FileMergeInlineDiffRequestDTO(
	/**
	 * See FileInRevisionDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val fileId: com.ecwid.upsource.rpc.ids.FileInRevisionDTO,

	/**
	 * The source revision from which the branch originated (required)
	 */
	val sourceRevisionId: String,

	/**
	 * The base branch to compare against (required)
	 */
	val baseBranch: String,

	/**
	 * Type of change (see DiffTypeEnum) (required)
	 */
	val diffType: DiffTypeEnum,

	/**
	 * Whether to ignore whitespace changes (required)
	 */
	val ignoreWhitespace: Boolean,

	/**
	 * Number of context lines around the modified fragment (optional)
	 */
	val contextLines: Int? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		fileId = com.ecwid.upsource.rpc.ids.FileInRevisionDTO(),
		sourceRevisionId = "",
		baseBranch = "",
		diffType = DiffTypeEnum.ADDED,
		ignoreWhitespace = false,
		contextLines = null
	)
}
