// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param diffType Type of change (see DiffTypeEnum)
 * @param revision See RevisionInfoDTO parameters
 * @param fileName A full path of the file starting with a slash (e.g. /folder/subfolder/file.txt )
 */
data class FileHistoryItemDTO(
	/**
	 * Type of change (see DiffTypeEnum) (required)
	 */
	val diffType: DiffTypeEnum,

	/**
	 * See RevisionInfoDTO parameters (required)
	 * 
	 * @see RevisionInfoDTO
	 */
	val revision: RevisionInfoDTO,

	/**
	 * A full path of the file starting with a slash (e.g. /folder/subfolder/file.txt ) (required)
	 */
	val fileName: String
) {
	internal constructor() : this(
		diffType = DiffTypeEnum.ADDED,
		revision = RevisionInfoDTO(),
		fileName = ""
	)
}
