// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param leftFile See FileInRevisionDTO parameters
 * @param rightFile See FileInRevisionDTO parameters
 * @param ignoreWhitespace Whether to ignore whitespace changes
 * @param isLeftFileDefinedAsNull Whether the left file for comparison is 'no-file' (for internal use only)
 * @param contextLines Number of context lines around the modified fragment
 */
@Suppress("unused")
data class FileDiffRequestDTO(
	/**
	 * See FileInRevisionDTO parameters (optional)
	 *
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val leftFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO? = null,

	/**
	 * See FileInRevisionDTO parameters (optional)
	 *
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val rightFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO? = null,

	/**
	 * Whether to ignore whitespace changes (required)
	 */
	val ignoreWhitespace: Boolean,

	/**
	 * Whether the left file for comparison is 'no-file' (for internal use only) (optional)
	 */
	val isLeftFileDefinedAsNull: Boolean? = null,

	/**
	 * Number of context lines around the modified fragment (optional)
	 */
	val contextLines: Int? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		leftFile = null,
		rightFile = null,
		ignoreWhitespace = false,
		isLeftFileDefinedAsNull = null,
		contextLines = null
	)
}

