// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param leftFile See FileInRevisionDTO parameters
 * @param rightFile See FileInRevisionDTO parameters
 * @param fragments See FileDiffFragmentDTO parameters
 */
@Suppress("unused")
data class FileDiffResponseDTO(
	/**
	 * See FileInRevisionDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val leftFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO? = null,

	/**
	 * See FileInRevisionDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val rightFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO? = null,

	/**
	 * See FileDiffFragmentDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FileDiffFragmentDTO
	 */
	val fragments: List<FileDiffFragmentDTO> = emptyList()
)