// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewId See ReviewIdDTO parameters
 * @param file See FileInRevisionDTO parameters
 */
data class FileInReviewDTO(
	/**
	 * See ReviewIdDTO parameters (required)
	 * 
	 * @see ReviewIdDTO
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO,

	/**
	 * See FileInRevisionDTO parameters (required)
	 * 
	 * @see FileInRevisionDTO
	 */
	val file: com.ecwid.upsource.rpc.ids.FileInRevisionDTO
) {
	internal constructor() : this(
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO(),
		file = com.ecwid.upsource.rpc.ids.FileInRevisionDTO()
	)
}
