// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param leftFileStartLine Line number to start with
 * @param leftFileLineCount How many lines
 * @param rightFileStartLine Line number to start with
 * @param rightFileLineCount How many lines
 * @param isUnchanged Indicates that a fragment is unchanged ("true" for unchanged commented lines)
 * @param addedRanges Ranges of text that were added
 * @param deletedRanges Ranges of text that were deleted
 */
data class FileDiffFragmentDTO(
	/**
	 * Line number to start with (required)
	 */
	val leftFileStartLine: Int,

	/**
	 * How many lines (required)
	 */
	val leftFileLineCount: Int,

	/**
	 * Line number to start with (required)
	 */
	val rightFileStartLine: Int,

	/**
	 * How many lines (required)
	 */
	val rightFileLineCount: Int,

	/**
	 * Indicates that a fragment is unchanged ("true" for unchanged commented lines) (required)
	 */
	val isUnchanged: Boolean,

	/**
	 * Ranges of text that were added (repeated)
	 */
	val addedRanges: List<com.ecwid.upsource.rpc.ids.RangeDTO> = emptyList(),

	/**
	 * Ranges of text that were deleted (repeated)
	 */
	val deletedRanges: List<com.ecwid.upsource.rpc.ids.RangeDTO> = emptyList()
) {
	internal constructor() : this(
		leftFileStartLine = 0,
		leftFileLineCount = 0,
		rightFileStartLine = 0,
		rightFileLineCount = 0,
		isUnchanged = false,
		addedRanges = emptyList(),
		deletedRanges = emptyList()
	)
}
