// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param retrospective See FileAnnotationSectionDTO parameters
 * @param perspective See FileAnnotationSectionDTO parameters
 */
data class FileAnnotationResponseDTO(
	/**
	 * See FileAnnotationSectionDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FileAnnotationSectionDTO
	 */
	val retrospective: List<FileAnnotationSectionDTO> = emptyList(),

	/**
	 * See FileAnnotationSectionDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FileAnnotationSectionDTO
	 */
	val perspective: List<FileAnnotationSectionDTO> = emptyList()
)