// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param commits See FindCommitsResponseCommitDTO parameters
 */
@Suppress("unused")
data class FindCommitsResponseCommitsDTO(
	/**
	 * See FindCommitsResponseCommitDTO parameters (repeated)
	 *
	 * @see com.ecwid.upsource.rpc.projects.FindCommitsResponseCommitDTO
	 */
	val commits: List<FindCommitsResponseCommitDTO> = emptyList()
)
