// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class FindCommitsResponseCommitsDTO(
	/**
	 * See FindCommitsResponseCommitDTO parameters (repeated)
	 */
	val commits: List<FindCommitsResponseCommitDTO> = emptyList()
)