// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param commits See FindCommitsResponseCommitDTO parameters
 */
data class FindCommitsResponseCommitsDTO(
	/**
	 * See FindCommitsResponseCommitDTO parameters (repeated)
	 * 
	 * @see FindCommitsResponseCommitDTO
	 */
	val commits: List<FindCommitsResponseCommitDTO> = emptyList()
)