// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param projectName Project name
 * @param revision See RevisionInfoDTO parameters
 * @param changes See RevisionsDiffDTO parameters
 */
@Suppress("unused")
data class FindCommitsResponseCommitDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Project name (required)
	 */
	val projectName: String,

	/**
	 * See RevisionInfoDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionInfoDTO
	 */
	val revision: RevisionInfoDTO,

	/**
	 * See RevisionsDiffDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionsDiffDTO
	 */
	val changes: RevisionsDiffDTO? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		projectName = "",
		revision = RevisionInfoDTO(),
		changes = null
	)
}

