// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param commits See FindCommitsResponseCommitsDTO parameters
 */
@Suppress("unused")
data class FindCommitsResponseDTO(
	/**
	 * See FindCommitsResponseCommitsDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FindCommitsResponseCommitsDTO
	 */
	val commits: List<FindCommitsResponseCommitsDTO> = emptyList()
)
