// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param errors 
 * @param warnings 
 * @param weakWarnings 
 * @param infos 
 */
data class InspectionsCountDTO(
	val errors: Int,

	val warnings: Int,

	val weakWarnings: Int,

	val infos: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		errors = 0,
		warnings = 0,
		weakWarnings = 0,
		infos = 0
	)
}
