// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param user See UserRolesDTO parameters
 * @param isInvited Whether the user is already invited
 */
@Suppress("unused")
data class InviteUserResponseDTO(
	/**
	 * See UserRolesDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.UserRolesDTO
	 */
	val user: UserRolesDTO? = null,

	/**
	 * Whether the user is already invited (required)
	 */
	val isInvited: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		user = null,
		isInvited = false
	)
}
