// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param id Discussion label ID
 * @param name Discussion label name (e.g. bug, code style, enhancement, help wanted)
 * @param colorId Discussion label color
 */
@Suppress("unused")
data class LabelDTO(
	/**
	 * Discussion label ID (optional)
	 */
	val id: String? = null,

	/**
	 * Discussion label name (e.g. bug, code style, enhancement, help wanted) (required)
	 */
	val name: String,

	/**
	 * Discussion label color (optional)
	 */
	val colorId: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		id = null,
		name = "",
		colorId = null
	)
}
