// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class LabelsRequestDTO(
	/**
	 * Project ID in Upsource (optional)
	 */
	val projectId: String? = null
)