// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param hidePredefinedLabels Indicates if predefined labels are hidden
 * @param predefinedLabels Predefined discussion labels. See LabelDTO parameters
 * @param customLabels Custom discussion labels. See LabelDTO parameters
 */
data class LabelsListDTO(
	/**
	 * Indicates if predefined labels are hidden (required)
	 */
	val hidePredefinedLabels: Boolean,

	/**
	 * Predefined discussion labels. See LabelDTO parameters (repeated)
	 * 
	 * @see LabelDTO
	 */
	val predefinedLabels: List<LabelDTO> = emptyList(),

	/**
	 * Custom discussion labels. See LabelDTO parameters (repeated)
	 * 
	 * @see LabelDTO
	 */
	val customLabels: List<LabelDTO> = emptyList()
) {
	internal constructor() : this(
		hidePredefinedLabels = false,
		predefinedLabels = emptyList(),
		customLabels = emptyList()
	)
}
