// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param participant An Upsource user ID of the participant
 * @param oldState See ParticipantStateEnum parameters
 * @param newState See ParticipantStateEnum parameters
 */
data class ParticipantStateChangedDTO(
	/**
	 * An Upsource user ID of the participant (required)
	 */
	val participant: String,

	/**
	 * See ParticipantStateEnum parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ParticipantStateEnum
	 */
	val oldState: ParticipantStateEnum,

	/**
	 * See ParticipantStateEnum parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ParticipantStateEnum
	 */
	val newState: ParticipantStateEnum
) {
	@Suppress("unused")
	internal constructor() : this(
		participant = "",
		oldState = ParticipantStateEnum.UNREAD,
		newState = ParticipantStateEnum.UNREAD
	)
}
