// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param userId User ID of the review participant
 * @param readFilesCount Number of files that were viewed by the participant
 * @param lastSeenTimestamp Unix timestamp of the last viewing
 */
data class ParticipantProgressDTO(
	/**
	 * User ID of the review participant (required)
	 */
	val userId: String,

	/**
	 * Number of files that were viewed by the participant (required)
	 */
	val readFilesCount: Int,

	/**
	 * Unix timestamp of the last viewing (required)
	 */
	val lastSeenTimestamp: Long
) {
	@Suppress("unused")
	internal constructor() : this(
		userId = "",
		readFilesCount = 0,
		lastSeenTimestamp = 0L
	)
}
