// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param displayName Display name of a project tree item
 * @param displayType Display type – directory, module, file, etc.
 * @param isDirectory Whether an item is a directory
 * @param isModule Whether an item is a module
 * @param fileId Path to file
 * @param hasChildren Whether an item has children and can be expanded
 */
@Suppress("unused")
data class ProjectTreeItemDTO(
	/**
	 * Display name of a project tree item (required)
	 */
	val displayName: String,

	/**
	 * Display type – directory, module, file, etc. (required)
	 */
	val displayType: String,

	/**
	 * Whether an item is a directory (required)
	 */
	val isDirectory: Boolean,

	/**
	 * Whether an item is a module (required)
	 */
	val isModule: Boolean,

	/**
	 * Path to file (required)
	 */
	val fileId: String,

	/**
	 * Whether an item has children and can be expanded (required)
	 */
	val hasChildren: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		displayName = "",
		displayType = "",
		isDirectory = false,
		isModule = false,
		fileId = "",
		hasChildren = false
	)
}

