// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param userId User ID of the person who created the project
 * @param date Unix timestamp of project creation
 */
@Suppress("unused")
data class ProjectFounderDTO(
	/**
	 * User ID of the person who created the project (required)
	 */
	val userId: String,

	/**
	 * Unix timestamp of project creation (required)
	 */
	val date: Long
) {
	@Suppress("unused")
	internal constructor() : this(
		userId = "",
		date = 0L
	)
}
