// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param name Name of the Hub group
 * @param description Description of the Hub group
 */
data class ProjectGroupDTO(
	/**
	 * Name of the Hub group (required)
	 */
	val name: String,

	/**
	 * Description of the Hub group (required)
	 */
	val description: String
) {
	internal constructor() : this(
		name = "",
		description = ""
	)
}
