// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param type Build system type ("none" to disable code intelligence, "maven" for Maven, "gradle" for Gradle, "idea" for IntelliJ IDEA)
 * @param pathToModel Path to project model
 * @param defaultJdkId Default project JDK
 */
@Suppress("unused")
data class ProjectModel(
	/**
	 * Build system type ("none" to disable code intelligence, "maven" for Maven, "gradle" for Gradle, "idea" for IntelliJ IDEA) (required)
	 */
	val type: String,

	/**
	 * Path to project model (optional)
	 */
	val pathToModel: String? = null,

	/**
	 * Default project JDK (optional)
	 */
	val defaultJdkId: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		type = "",
		pathToModel = null,
		defaultJdkId = null
	)
}
