// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param items See ProjectTreeItemDTO parameters
 */
@Suppress("unused")
data class ProjectItemsListDTO(
	/**
	 * See ProjectTreeItemDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ProjectTreeItemDTO
	 */
	val items: List<ProjectTreeItemDTO> = emptyList()
)
