// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param text Text of the README file
 * @param fileName A full path to the README file starting with a slash (e.g. /directory/readme.txt)
 * @param revisionId Revision ID
 */
data class ProjectReadmeResponseDTO(
	/**
	 * Text of the README file (required)
	 */
	val text: String,

	/**
	 * A full path to the README file starting with a slash (e.g. /directory/readme.txt) (required)
	 */
	val fileName: String,

	/**
	 * Revision ID (required)
	 */
	val revisionId: String
) {
	internal constructor() : this(
		text = "",
		fileName = "",
		revisionId = ""
	)
}
