// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class ReactionDTO(
	/**
	 * ID of the reaction (required)
	 */
	val id: String,

	/**
	 * List of Upsource user IDs (repeated)
	 */
	val usersIds: List<String> = emptyList()
) {
	internal constructor() : this(
		id = "",
		usersIds = emptyList()
	)
}
