// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param id ID of the reaction
 * @param usersIds List of Upsource user IDs
 */
@Suppress("unused")
data class ReactionDTO(
	/**
	 * ID of the reaction (required)
	 */
	val id: String,

	/**
	 * List of Upsource user IDs (repeated)
	 */
	val usersIds: List<String> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		id = "",
		usersIds = emptyList()
	)
}
