// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param syncResult GitHub sync result. See SyncResultEnum parameters
 */
data class ResolveDiscussionResponseDTO(
	/**
	 * GitHub sync result. See SyncResultEnum parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.SyncResultEnum
	 */
	val syncResult: SyncResultEnum? = null
)