// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param position Node position index
 * @param color Node color
 */
data class RevisionListGraphNodeDTO(
	/**
	 * Node position index (required)
	 */
	val position: Int,

	/**
	 * Node color (required)
	 */
	val color: Int
) {
	internal constructor() : this(
		position = 0,
		color = 0
	)
}
