// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revision See RevisionInProjectDTO parameters
 * @param compareToRevisionId ID of the revision to compare with
 * @param limit How many files to return
 * @param skip Number of files to skip from the top (for pagination)
 */
@Suppress("unused")
data class RevisionChangesRequestDTO(
	/**
	 * See RevisionInProjectDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.RevisionInProjectDTO
	 */
	val revision: com.ecwid.upsource.rpc.ids.RevisionInProjectDTO,

	/**
	 * ID of the revision to compare with (optional)
	 */
	val compareToRevisionId: String? = null,

	/**
	 * How many files to return (required)
	 */
	val limit: Int,

	/**
	 * Number of files to skip from the top (for pagination) (optional)
	 */
	val skip: Int? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		revision = com.ecwid.upsource.rpc.ids.RevisionInProjectDTO(),
		compareToRevisionId = null,
		limit = 0,
		skip = null
	)
}

