// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class RevisionReviewInfoListDTO(
	/**
	 * See RevisionReviewInfoDTO parameters (repeated)
	 */
	val reviewInfo: List<RevisionReviewInfoDTO> = emptyList()
)