// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviews See ReviewDescriptorDTO parameters
 * @param hasMore Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request
 * @param totalCount Total number of reviews
 */
data class ReviewListDTO(
	/**
	 * See ReviewDescriptorDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ReviewDescriptorDTO
	 */
	val reviews: List<ReviewDescriptorDTO> = emptyList(),

	/**
	 * Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request (required)
	 */
	val hasMore: Boolean,

	/**
	 * Total number of reviews (required)
	 */
	val totalCount: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		reviews = emptyList(),
		hasMore = false,
		totalCount = 0
	)
}
