// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param diff See RevisionDiffItemDTO parameters
 */
@Suppress("unused")
data class RevisionsDiffDTO(
	/**
	 * See RevisionDiffItemDTO parameters (repeated)
	 *
	 * @see com.ecwid.upsource.rpc.projects.RevisionDiffItemDTO
	 */
	val diff: List<RevisionDiffItemDTO> = emptyList()
)
