// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revisionOwner See RevisionOwnershipSummaryDTO
 */
@Suppress("unused")
data class RevisionsOwnershipSummaryDTO(
	/**
	 * See RevisionOwnershipSummaryDTO (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionOwnershipSummaryDTO
	 */
	val revisionOwner: List<RevisionOwnershipSummaryDTO> = emptyList()
)