// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class RevisionReviewInfoDTO(
	/**
	 * See ShortReviewInfoDTO parameters (optional)
	 */
	val reviewInfo: ShortReviewInfoDTO? = null
)