// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param diff See RevisionExternalInspectionsDiffResponseDTO
 */
@Suppress("unused")
data class RevisionsExternalInspectionsDiffResponseDTO(
	/**
	 * See RevisionExternalInspectionsDiffResponseDTO (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionExternalInspectionsDiffResponseDTO
	 */
	val diff: List<RevisionExternalInspectionsDiffResponseDTO> = emptyList()
)