// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class RevisionsDiffDTO(
	/**
	 * See RevisionDiffItemDTO parameters (repeated)
	 */
	val diff: List<RevisionDiffItemDTO> = emptyList()
)