// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param files See FileOwnershipSummaryDTO parameters
 */
data class ReviewOwnershipSummaryDTO(
	/**
	 * See FileOwnershipSummaryDTO parameters (repeated)
	 * 
	 * @see FileOwnershipSummaryDTO
	 */
	val files: List<FileOwnershipSummaryDTO> = emptyList()
)