// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param width "Width" of a graph, i.e. how many branches running in parallel does it have
 * @param rows See RevisionListGraphRowDTO parameters
 */
data class RevisionListGraphDTO(
	/**
	 * "Width" of a graph, i.e. how many branches running in parallel does it have (required)
	 */
	val width: Int,

	/**
	 * See RevisionListGraphRowDTO parameters (repeated)
	 * 
	 * @see RevisionListGraphRowDTO
	 */
	val rows: List<RevisionListGraphRowDTO> = emptyList()
) {
	internal constructor() : this(
		width = 0,
		rows = emptyList()
	)
}
