// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewInfo See ShortReviewInfoDTO parameters
 */
data class RevisionReviewInfoDTO(
	/**
	 * See ShortReviewInfoDTO parameters (optional)
	 * 
	 * @see ShortReviewInfoDTO
	 */
	val reviewInfo: ShortReviewInfoDTO? = null
)