// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revisions IDs of the requested revisions
 * @param selectAll Set this to "true" to request all revisions without enumerating them
 */
@Suppress("unused")
data class RevisionsSetDTO(
	/**
	 * IDs of the requested revisions (repeated)
	 */
	val revisions: List<String> = emptyList(),

	/**
	 * Set this to "true" to request all revisions without enumerating them (optional)
	 */
	val selectAll: Boolean? = null
)