// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewId See ReviewIdDTO parameters
 * @param revisions See RevisionsSetDTO parameters
 */
data class ReviewSummaryDiscussionsRequestDTO(
	/**
	 * See ReviewIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.ReviewIdDTO
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO,

	/**
	 * See RevisionsSetDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionsSetDTO
	 */
	val revisions: RevisionsSetDTO? = null
) {
	internal constructor() : this(
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO(),
		revisions = null
	)
}
