// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewInfo See RevisionReviewInfoDTO parameters
 */
data class RevisionReviewInfoListDTO(
	/**
	 * See RevisionReviewInfoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionReviewInfoDTO
	 */
	val reviewInfo: List<RevisionReviewInfoDTO> = emptyList()
)