// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param revision See RevisionInfoDTO parameters
 * @param graph See RevisionListGraphDTO parameters
 * @param headHash Head revision ID
 * @param query Search query
 */
data class RevisionDescriptorListDTO(
	/**
	 * See RevisionInfoDTO parameters (repeated)
	 * 
	 * @see RevisionInfoDTO
	 */
	val revision: List<RevisionInfoDTO> = emptyList(),

	/**
	 * See RevisionListGraphDTO parameters (optional)
	 * 
	 * @see RevisionListGraphDTO
	 */
	val graph: RevisionListGraphDTO? = null,

	/**
	 * Head revision ID (optional)
	 */
	val headHash: String? = null,

	/**
	 * Search query (optional)
	 */
	val query: String? = null
)