// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewInfo See ShortReviewInfoDTO parameters
 */
@Suppress("unused")
data class RevisionReviewInfoDTO(
	/**
	 * See ShortReviewInfoDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ShortReviewInfoDTO
	 */
	val reviewInfo: ShortReviewInfoDTO? = null
)
