// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param diffType See DiffTypeEnum parameters
 * @param newFile See FileInRevisionDTO parameters
 * @param oldFile See FileInRevisionDTO parameters
 * @param fileIcon Indicates type of file (e.g. "file:xml")
 * @param isRead Whether the diff has been viewed by the user. When returned by the findCommits method, isRead is always set to 'true'.
 * @param conflictType When the diff relates to the merge result, holds the conflict type (see ConflictTypeEnum)
 */
data class RevisionDiffItemDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * See DiffTypeEnum parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.DiffTypeEnum
	 */
	val diffType: DiffTypeEnum,

	/**
	 * See FileInRevisionDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val newFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO,

	/**
	 * See FileInRevisionDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.FileInRevisionDTO
	 */
	val oldFile: com.ecwid.upsource.rpc.ids.FileInRevisionDTO? = null,

	/**
	 * Indicates type of file (e.g. "file:xml") (optional)
	 */
	val fileIcon: String? = null,

	/**
	 * Whether the diff has been viewed by the user. When returned by the findCommits method, isRead is always set to 'true'. (required)
	 */
	val isRead: Boolean,

	/**
	 * When the diff relates to the merge result, holds the conflict type (see ConflictTypeEnum) (optional)
	 */
	val conflictType: ConflictTypeEnum? = null
) {
	internal constructor() : this(
		projectId = "",
		diffType = DiffTypeEnum.ADDED,
		newFile = com.ecwid.upsource.rpc.ids.FileInRevisionDTO(),
		oldFile = null,
		fileIcon = null,
		isRead = false,
		conflictType = null
	)
}
