// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param diff See RevisionsDiffDTO parameters
 * @param annotation Review annotation message, e.g. "Some revisions in review are not indexed yet", "Review has too many files"
 * @param ignoredFiles The list of files that were omitted in a review according to project settings
 * @param fileDiffSummary See FileDiffSummaryDTO parameters
 */
data class ReviewSummaryChangesResponseDTO(
	/**
	 * See RevisionsDiffDTO parameters (optional)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RevisionsDiffDTO
	 */
	val diff: RevisionsDiffDTO? = null,

	/**
	 * Review annotation message, e.g. "Some revisions in review are not indexed yet", "Review has too many files" (optional)
	 */
	val annotation: String? = null,

	/**
	 * The list of files that were omitted in a review according to project settings (repeated)
	 */
	val ignoredFiles: List<String> = emptyList(),

	/**
	 * See FileDiffSummaryDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.FileDiffSummaryDTO
	 */
	val fileDiffSummary: List<FileDiffSummaryDTO> = emptyList()
)