// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param id Role ID
 * @param key Role key (e.g. project-admin)
 * @param name Role name (e.g. Project admin)
 * @param description Role description
 */
data class RoleDetailsDTO(
	/**
	 * Role ID (required)
	 */
	val id: String,

	/**
	 * Role key (e.g. project-admin) (required)
	 */
	val key: String,

	/**
	 * Role name (e.g. Project admin) (required)
	 */
	val name: String,

	/**
	 * Role description (optional)
	 */
	val description: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		id = "",
		key = "",
		name = "",
		description = null
	)
}
