// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param html The HTML string to sanitize
 * @param isBasicMarkup "true" allows only basic HTML markup (text formatting, images, links), "false" additionally allows block-level HTML elements and tables
 */
data class SanitizeHTMLRequestDTO(
	/**
	 * The HTML string to sanitize (required)
	 */
	val html: String,

	/**
	 * "true" allows only basic HTML markup (text formatting, images, links), "false" additionally allows block-level HTML elements and tables (required)
	 */
	val isBasicMarkup: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		html = "",
		isBasicMarkup = false
	)
}
