// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param sanitizedHTML Sanitized HTML string
 */
@Suppress("unused")
data class SanitizeHTMLResponseDTO(
	/**
	 * Sanitized HTML string (required)
	 */
	val sanitizedHTML: String
) {
	@Suppress("unused")
	internal constructor() : this(
		sanitizedHTML = ""
	)
}
