// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class SanitizeHTMLResponseDTO(
	/**
	 * Sanitized HTML string (required)
	 */
	val sanitizedHTML: String
) {
	internal constructor() : this(
		sanitizedHTML = ""
	)
}
