// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param project See ShortProjectInfoDTO parameters
 */
data class ShortProjectInfoListDTO(
	/**
	 * See ShortProjectInfoDTO parameters (repeated)
	 * 
	 * @see ShortProjectInfoDTO
	 */
	val project: List<ShortProjectInfoDTO> = emptyList()
)