// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class ShortProjectInfoListDTO(
	/**
	 * See ShortProjectInfoDTO parameters (repeated)
	 */
	val project: List<ShortProjectInfoDTO> = emptyList()
)