// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param count Total number of discussions
 * @param hasUnresolved Contains unresolved discussions
 * @param unresolvedCount Number of unresolved discussions
 * @param resolvedCount Number of resolved discussions
 */
@Suppress("unused")
data class SimpleDiscussionCounterDTO(
	/**
	 * Total number of discussions (required)
	 */
	val count: Int,

	/**
	 * Contains unresolved discussions (required)
	 */
	val hasUnresolved: Boolean,

	/**
	 * Number of unresolved discussions (required)
	 */
	val unresolvedCount: Int,

	/**
	 * Number of resolved discussions (required)
	 */
	val resolvedCount: Int
) {
	@Suppress("unused")
	internal constructor() : this(
		count = 0,
		hasUnresolved = false,
		unresolvedCount = 0,
		resolvedCount = 0
	)
}
