// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param lineNumber Line number that corresponds to the given stacktrace
 * @param fullPath A full path of the file
 * @param vcsCommitId Revision ID
 * @param interpolatedRange See RangeDTO parameters
 */
data class StacktracePositionDTO(
	/**
	 * Line number that corresponds to the given stacktrace (required)
	 */
	val lineNumber: Int,

	/**
	 * A full path of the file (required)
	 */
	val fullPath: String,

	/**
	 * Revision ID (optional)
	 */
	val vcsCommitId: String? = null,

	/**
	 * See RangeDTO parameters (optional)
	 * 
	 * @see RangeDTO
	 */
	val interpolatedRange: com.ecwid.upsource.rpc.ids.RangeDTO? = null
) {
	internal constructor() : this(
		lineNumber = 0,
		fullPath = "",
		vcsCommitId = null,
		interpolatedRange = null
	)
}
