// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewId Review ID
 * @param branch Branch name to track
 */
@Suppress("unused")
data class StartBranchTrackingRequestDTO(
	/**
	 * Review ID (required)
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO,

	/**
	 * Branch name to track (required)
	 */
	val branch: String
) {
	@Suppress("unused")
	internal constructor() : this(
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO(),
		branch = ""
	)
}

