// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewId Review ID
 * @param branch Branch name to stop tracking. When none specified, tracking of all branches will stop.
 */
data class StopBranchTrackingRequestDTO(
	/**
	 * Review ID (required)
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO,

	/**
	 * Branch name to stop tracking. When none specified, tracking of all branches will stop. (optional)
	 */
	val branch: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO(),
		branch = null
	)
}
