// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param suggest 
 */
data class SuggestedRevisionListDTO(
	val suggest: List<RevisionSuggestDTO> = emptyList()
)