// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID
 * @param vcsSettings VCS configuration represented as a JSON-encoded string
 */
data class TestConnectionRequestDTO(
	/**
	 * Project ID (optional)
	 */
	val projectId: String? = null,

	/**
	 * VCS configuration represented as a JSON-encoded string (required)
	 */
	val vcsSettings: String
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = null,
		vcsSettings = ""
	)
}
