// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param parentRevisionId Parent revision ID
 * @param files List of modified files (added, deleted, updated)
 */
@Suppress("unused")
data class UncommittedRevisionDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Parent revision ID (required)
	 */
	val parentRevisionId: String,

	/**
	 * List of modified files (added, deleted, updated) (repeated)
	 */
	val files: List<String> = emptyList()
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		parentRevisionId = "",
		files = emptyList()
	)
}
