// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param reviewId See ReviewIdDTO parameters
 * @param state State of the participant. See ParticipantStateEnum parameters
 * @param userId User ID. When set, this user's participant state will be changed.
 */
@Suppress("unused")
data class UpdateParticipantInReviewRequestDTO(
	/**
	 * See ReviewIdDTO parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.ids.ReviewIdDTO
	 */
	val reviewId: com.ecwid.upsource.rpc.ids.ReviewIdDTO,

	/**
	 * State of the participant. See ParticipantStateEnum parameters (required)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.ParticipantStateEnum
	 */
	val state: ParticipantStateEnum,

	/**
	 * User ID. When set, this user's participant state will be changed. (optional)
	 */
	val userId: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		reviewId = com.ecwid.upsource.rpc.ids.ReviewIdDTO(),
		state = ParticipantStateEnum.UNREAD,
		userId = null
	)
}

