// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 * @param discussionId An ID of the discussion being updated
 * @param commentId An ID of the comment being updated
 * @param text New text of the comment being updated
 * @param markupType Currently not in use
 */
data class UpdateCommentRequestDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * An ID of the discussion being updated (required)
	 */
	val discussionId: String,

	/**
	 * An ID of the comment being updated (required)
	 */
	val commentId: String,

	/**
	 * New text of the comment being updated (required)
	 */
	val text: String,

	/**
	 * Currently not in use (optional)
	 */
	val markupType: String? = null
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		discussionId = "",
		commentId = "",
		text = "",
		markupType = null
	)
}
