// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param label The review label
 * @param syncResult GitHub sync result. See SyncResultEnum parameters
 */
data class UpdateReviewLabelResponseDTO(
	/**
	 * The review label (required)
	 */
	val label: LabelDTO,

	/**
	 * GitHub sync result. See SyncResultEnum parameters (optional)
	 * 
	 * @see SyncResultEnum
	 */
	val syncResult: SyncResultEnum? = null
) {
	internal constructor() : this(
		label = LabelDTO(),
		syncResult = null
	)
}
