// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param userRoles See UserRolesDTO parameters
 * @param hasMore Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request
 */
data class UsersRolesResponseDTO(
	/**
	 * See UserRolesDTO parameters (repeated)
	 * 
	 * @see UserRolesDTO
	 */
	val userRoles: List<UserRolesDTO> = emptyList(),

	/**
	 * Whether all available items have been returned or more can be requested by passing the corresponding 'limit' value in the subsequent request (required)
	 */
	val hasMore: Boolean
) {
	internal constructor() : this(
		userRoles = emptyList(),
		hasMore = false
	)
}
