// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param userId ID of the Upsource user
 * @param roles See RoleDTO parameters
 */
data class UserRolesDTO(
	/**
	 * ID of the Upsource user (required)
	 */
	val userId: String,

	/**
	 * See RoleDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.RoleDTO
	 */
	val roles: List<RoleDTO> = emptyList()
) {
	internal constructor() : this(
		userId = "",
		roles = emptyList()
	)
}
