// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

data class UserRolesDTO(
	/**
	 * ID of the Upsource user (required)
	 */
	val userId: String,

	/**
	 * See RoleDTO parameters (repeated)
	 */
	val roles: List<RoleDTO> = emptyList()
) {
	internal constructor() : this(
		userId = "",
		roles = emptyList()
	)
}
