// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param service See VcsHostingServiceDTO parameters
 */
data class VcsHostingResponseDTO(
	/**
	 * See VcsHostingServiceDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.VcsHostingServiceDTO
	 */
	val service: List<VcsHostingServiceDTO> = emptyList()
)