// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param projectId Project ID in Upsource
 */
@Suppress("unused")
data class VcsHostingRequestDTO(
	/**
	 * Project ID in Upsource (optional)
	 */
	val projectId: String? = null
)