// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param serviceId VCS hosting service ID
 * @param serviceUrl VCS hosting service URL
 * @param repoIds IDs of the VCS repositories
 * @param canCreateRepository Whether the requester has permission to create repositories in the VCS service
 */
data class VcsHostingServiceDTO(
	/**
	 * VCS hosting service ID (required)
	 */
	val serviceId: String,

	/**
	 * VCS hosting service URL (required)
	 */
	val serviceUrl: String,

	/**
	 * IDs of the VCS repositories (repeated)
	 */
	val repoIds: List<String> = emptyList(),

	/**
	 * Whether the requester has permission to create repositories in the VCS service (required)
	 */
	val canCreateRepository: Boolean
) {
	@Suppress("unused")
	internal constructor() : this(
		serviceId = "",
		serviceUrl = "",
		repoIds = emptyList(),
		canCreateRepository = false
	)
}
