// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.projects

/**
 * @param repo See VcsRepoDTO parameters
 */
@Suppress("unused")
data class VcsRepoListDTO(
	/**
	 * See VcsRepoDTO parameters (repeated)
	 * 
	 * @see com.ecwid.upsource.rpc.projects.VcsRepoDTO
	 */
	val repo: List<VcsRepoDTO> = emptyList()
)
