// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

/**
 * @param projectId Project ID in Upsource
 */
@Suppress("unused")
data class ProjectIdListDTO(
	/**
	 * Project ID in Upsource (repeated)
	 */
	val projectId: List<String> = emptyList()
)