// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

data class ProjectIdDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String
) {
	internal constructor() : this(
		projectId = ""
	)
}
