// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

/**
 * @param projectId Project ID in Upsource
 * @param reviewId Review ID assigned to it when it's created
 */
@Suppress("unused")
data class ReviewIdDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * Review ID assigned to it when it's created (required)
	 */
	val reviewId: String
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		reviewId = ""
	)
}

