// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

/**
 * @param projectId Project ID in Upsource
 * @param revisionId VCS revision ID
 */
data class RevisionInProjectDTO(
	/**
	 * Project ID in Upsource (required)
	 */
	val projectId: String,

	/**
	 * VCS revision ID (required)
	 */
	val revisionId: String
) {
	@Suppress("unused")
	internal constructor() : this(
		projectId = "",
		revisionId = ""
	)
}
