// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

/**
 * @param revisionId VCS revision ID
 */
data class RevisionIdDTO(
	/**
	 * VCS revision ID (required)
	 */
	val revisionId: String
) {
	internal constructor() : this(
		revisionId = ""
	)
}
