// Generated by the codegen. Please DO NOT EDIT!
// source: message.ftl

package com.ecwid.upsource.rpc.ids

/**
 * @param voidField No value required/returned
 */
@Suppress("unused")
data class VoidMessage(
	/**
	 * No value required/returned (optional)
	 */
	val voidField: Int? = null
)
