package com.ecwid.upsource.codegen.templates

import freemarker.cache.ClassTemplateLoader
import freemarker.template.Configuration
import freemarker.template.Configuration.VERSION_2_3_30
import java.io.StringWriter

private const val DO_NOT_EDIT_PREFIX = "// Generated by the codegen. Please DO NOT EDIT!"

class Templates {
	private val configuration = Configuration(VERSION_2_3_30)

	init {
		configuration.defaultEncoding = "UTF-8"
		configuration.templateLoader = ClassTemplateLoader(javaClass.classLoader, "templates")
	}

	fun render(template: Template): String {
		val processor = configuration.getTemplate(template.filename)
		val writer = StringWriter()
		writer.use {
			it.write("$DO_NOT_EDIT_PREFIX\n// source: ${template.filename}\n\n")

			processor.process(template, it)
		}
		return writer.toString()
	}
}
